{
 "title": "Ceph - S3 Bucket Metrics",
 "description": "S3 bucket ops, sizes, trends, etc. and overall Ceph activity.",
 "tags": [
  "ceph",
  "s3",
  "radosgw"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(ceph_rgw_op_per_bucket_get_obj_ops,bucket)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(ceph_mon_quorum_status,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GET Operations per S3 Bucket (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (bucket) (increase(ceph_rgw_op_per_bucket_get_obj_ops{bucket=~\"$bucket\"}[1m])/60)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "PUT Operations per S3 Bucket (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (bucket) (increase(ceph_rgw_op_per_bucket_put_obj_ops{bucket=~\"$bucket\"}[1m])/60)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Other S3 Bucket Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "LIST Operations per S3 Bucket (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (bucket) (increase(ceph_rgw_op_per_bucket_list_obj_ops{bucket=~\"$bucket\"}[1m])/60)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DELETE Operations per S3 Bucket (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (bucket) (increase(ceph_rgw_op_per_bucket_del_obj_ops{bucket=~\"$bucket\"}[1m])/60)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "COPY Operations per S3 Bucket (ops/min)",
     "type": "timeseries",
     "description": "Per minute instead of per second.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (bucket) (increase(ceph_rgw_op_per_bucket_copy_obj_ops{bucket=~\"$bucket\"}[1m]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET Operations per S3 User (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_user_get_obj_ops{user=~\".*\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "PUT Operations per user (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_user_put_obj_ops{user=~\".*\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "LIST Operations per user (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_user_list_obj_ops{user=~\".*\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "DELETE Operations per user (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_user_del_obj_ops{user=~\".*\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "COPY Operations per user (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_user_copy_obj_ops{user=~\".*\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Bucket Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Bucket Sizes",
     "type": "timeseries",
     "description": "Raw, unreplicated.",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Storage Usage",
     "type": "gauge",
     "description": "Actual (raw - thats how much data is generated) and Replicated (thats how much storage is needed for it).",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776)",
       "legendFormat": "Raw"
      },
      {
       "expr": "(sum(radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776))*3",
       "legendFormat": "Replicated"
      }
     ]
    },
    {
     "title": "S3 Objects (Thousands)",
     "type": "timeseries",
     "description": "The number of objects within S3 buckets, multiply by 1000 to get exact value.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_objects{bucket=~\"$bucket\"}/1000",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket Shards",
     "type": "timeseries",
     "description": "11 - default shards. We recomed for 100k objects per 1 shard for best S3 performance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_shards{bucket=~\"$bucket\", bucket!=\"-\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Data Read Volume",
     "type": "timeseries",
     "description": "GET operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "GB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(ceph_rgw_op_per_bucket_get_obj_bytes{bucket=~\"$bucket\"}[1m]) / 1073741824)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Data Write Volume",
     "type": "timeseries",
     "description": "PUT Operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "GB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(ceph_rgw_op_per_bucket_put_obj_bytes{bucket=~\"$bucket\"}[1m])) / 1073741824",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Data Delete Volume",
     "type": "timeseries",
     "description": "DELETE Operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "MB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(ceph_rgw_op_per_bucket_del_obj_bytes{bucket=~\"$bucket\"}[1m])) / 1048576",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Data Copy Volume",
     "type": "timeseries",
     "description": "COPY Operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "MB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(ceph_rgw_op_per_bucket_copy_obj_bytes{bucket=~\"$bucket\"}[1m])) / 1048576",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Timeouts - Data Platform",
     "type": "timeseries",
     "description": "Haproxy 500 responses from data-k8s",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(haproxy_backend_http_responses_total{code=\"5xx\",k8s_cluster=\"data-k8s\"}[2m])",
       "legendFormat": "{{ k8s_node_name }}:  {{ k8s_pod_name }}  "
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Bucket GET Latency",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_bucket_get_obj_lat_sum{bucket!=\"borg-backup\"}[1m])) by (bucket)\n/\nsum(rate(ceph_rgw_op_per_bucket_get_obj_lat_count{bucket!=\"borg-backup\"}[1m])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket PUT Latency",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_bucket_put_obj_lat_sum[1m])) by (bucket)\n/\nsum(rate(ceph_rgw_op_per_bucket_put_obj_lat_count[1m])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket LIST Latency",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_bucket_list_obj_lat_sum[1m])) by (bucket)\n/\nsum(rate(ceph_rgw_op_per_bucket_list_obj_lat_count[1m])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket DELETE Latency",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_bucket_del_obj_lat_sum[1m])) by (bucket)\n/\nsum(rate(ceph_rgw_op_per_bucket_del_obj_lat_count[1m])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket COPY Latency",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_op_per_bucket_copy_obj_lat_sum[1m])) by (bucket)\n/\nsum(rate(ceph_rgw_op_per_bucket_copy_obj_lat_count[1m])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Activity Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Total Requests (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ceph_rgw_req{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")\n",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 GET Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_get_obj_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 PUT Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_put_obj_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 DELETE (Objects) Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_del_obj_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 DELETE (Buckets) Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_del_bucket_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 LIST (Objects) Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_list_obj_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 LIST (Buckets) Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_list_buckets_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "S3 COPY Request Rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(ceph_rgw_op_copy_obj_ops{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Cluster Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph Scrubs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "pgs" } },
     "targets": [
      { "expr": "sum(ceph_pg_scrubbing) by (pg)", "legendFormat": "Overall Cluster Scrubs" },
      {
       "expr": "sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data Shallow Scrubs"
      },
      {
       "expr": "sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data Deep Scrubs"
      },
      {
       "expr": "(sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg))+(sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg))",
       "legendFormat": "RadosGW Metadata Scrubs"
      },
      {
       "expr": "(sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg))+(sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg))",
       "legendFormat": "S3 Index Scrubs"
      },
      {
       "expr": "((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)))",
       "legendFormat": "Other Pool Scrubs"
      }
     ]
    },
    {
     "title": "Ceph Backfills",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pgs" } },
     "targets": [
      {
       "expr": "sum(ceph_pg_backfilling) by (pg)",
       "legendFormat": "All Placement Groups"
      },
      {
       "expr": "(sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)))",
       "legendFormat": "S3 Bucket Placement Groups"
      },
      {
       "expr": "(sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)))",
       "legendFormat": "RadosGW Placement Groups"
      }
     ]
    },
    {
     "title": "Ceph S3 Active Placement Groups (Pools)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_pg_active) by (pg)", "legendFormat": "Cluster Total PGs" },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg)",
       "legendFormat": "Metadata PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg)",
       "legendFormat": "Index PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)",
       "legendFormat": "Log PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)",
       "legendFormat": "Non-EC PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)",
       "legendFormat": "Control PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)",
       "legendFormat": "Root PGs"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Disk Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Overall Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "read"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "write"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "overwrite"
      }
     ]
    },
    {
     "title": "Commit Latency - per OSD",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Apply Latency - per OSD",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Read Latency - sum per 1 min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Total Ops History per OSD",
     "type": "timeseries",
     "description": "A counter to see which disks have been used the most",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "ceph_osd_op{job=\"ceph-cluster\"}",
       "legendFormat": "Disk: {{ceph_daemon}}"
      }
     ]
    }
   ]
  }
 ]
}